### ISSUE TITLE
Part 1: rails-project example - Bundler could not find compatible versions for gem "mimemagic"

### ISSUE THREAD

**Issue by mnajjarian** [docker-hy/docker-hy.github.io#109]
Run 'bundle install' gets the error: "Your bundle is locked to mimemagic (0.3.5), but that version could not be found..."

This can be fixed with run 'bundle update mimemagic' before 'bundle install'.

**Comment by Jakousa** [comment]
Should be fixed by this commit in the project itself https://github.com/docker-hy/material-applications/commit/8f70d4e88d18979e86d9213b6d0b8b485471990e
