### ISSUE TITLE
DSLError while buidling course material

### ISSUE THREAD

**Issue by akirataguchi115** [docker-hy/docker-hy.github.io#129]
![image](https://user-images.githubusercontent.com/31825085/138546518-8f46df8f-8027-424e-818b-5327dd2223bb.png)

Pretty sure this has something to do with these two: https://stackoverflow.com/questions/57926553/bundle-install-gives-bundlerdsldslerror
https://medium.com/@tahteche/how-git-treats-changes-in-file-permissions-f71874ca239d

`chmod 644 Gemfile` and `chmod 644 Gemfile.lock` fixed the issue.

Not sure whether the issue should be tackled within Dockerfile or just make a note into the building instructions, hence why I'm just creating this issue.

**Comment by mluukkai** [comment]
no more jekyll
