### ISSUE TITLE
tutum no longer exists

### ISSUE THREAD

**Issue by matti** [docker-hy/docker-hy.github.io#136]
>The third result, tutum/hello-world, is marked as “automated”. This means that the image is automatically built from the source repository. Its Docker Hub page shows its previous “Builds” and a link to the image’s “Source Repository” (in this case, to GitHub) from which Docker Hub builds the image.

tutum has been removed from the internets

**Comment by akirataguchi115** [comment]
![image](https://user-images.githubusercontent.com/31825085/195416883-1a094582-6434-4f14-83d3-4c9c4b491da6.png)
tutum is alive and well
