### ISSUE TITLE
Part 1: Ruby project example - RUN rake assets:precompile fails

### ISSUE THREAD

**Issue by OmarMuhammedAli** [docker-hy/docker-hy.github.io#141]
Compilation always fails at the last step at `[10/10] RUN rake assets:precompile`

I tried several solutions to go about this issue:
- I specified certain versions of yarn as per https://github.com/yarnpkg/yarn/issues/8358
- I tried to explicitly install webpack, as part of the error message states that `Command "webpack" could not be found`
- I tried `RUN yarn install` to generate `node_modules` as per https://stackoverflow.com/a/60700426/13756013

## To reproduce
- I followed exactly how `Dockerfile` is created right before 1.11
- run `docker build . -t ruby-project`

### Output
![image](https://user-images.githubusercontent.com/53264297/144774496-7c7d8235-7f51-451a-9b40-a5e25fc93ac8.png)

Any help would be appreciated!

**Comment by qzuw** [comment]
Note several references in your screenshot (surely not "expected output") to \r, including warning that it may cause problems.

Set your IDE/text editor line endings to \n or LF only, or save text files in unix format.

**Comment by OmarMuhammedAli** [comment]
Thanks, @qzuw !
