### ISSUE TITLE
1.4 exercise instructions

### ISSUE THREAD

**Issue by Rochet2** [docker-hy/docker-hy.github.io#15]
The exercise 1.4 explicitly tells you to run `docker run curler` command.
However at least in my solution I had to use additional switches to be able to input anything to the running program.

I am unsure if the exercise can be done without switches with the material so far.
The material has not yet at that point covered the ENTRYPOINT and CMD differences, so using helsinki.fi as the input directly to the docker run command should probably not be expected from the student.

I would suggest adding the required switches to the instructions or a hint about them since the exercise is probably more about Dockerfile. No need to add anything if you feel like people will find out by themselves :)

**Comment by Jakousa** [comment]
Excellent points. I decided to add COPY so that it's easy to default to CMD. The flags were in 1.3 so I added a little nudge to remember them for interactive tty. https://github.com/docker-hy/docker-hy.github.io/commit/09f73f2fc0b1cd4d9ed5f5b739c645e60ea2098e
