### ISSUE TITLE
Can't build course material

### ISSUE THREAD

**Issue by akirataguchi115** [docker-hy/docker-hy.github.io#181]
![image](https://user-images.githubusercontent.com/31825085/195977194-f882ef01-2467-4bfa-8384-9fce3376f28c.png)

**Comment by mluukkai** [comment]
works with v16.19.0

**Comment by akirataguchi115** [comment]
@mluukkai I must be missing something here.
![image](https://user-images.githubusercontent.com/31825085/220917876-b3a0d13d-9b48-44f5-809c-3f18f7c72c7f.png)

**Comment by Jakousa** [comment]
Dockerfile fixed in https://github.com/docker-hy/docker-hy.github.io/commit/e75d098c5ef73d31acb6c489f4101f8888380084

And the build pipeline fixed in https://github.com/docker-hy/docker-hy.github.io/commit/0922e19d3d64221af226e197b1f043ba8e2f0e30
