### ISSUE TITLE
Inaccessiable link

### ISSUE THREAD

**Issue by kristianka** [docker-hy/docker-hy.github.io#250]
https://devopswithdocker.com/part-2/section-4/

In the second paragraph's first sentence, the second hyperlink https://ethesis.helsinki.fi/repository/handle/123456789/30995 seems to be locked. Is there a public version of this?

**Comment by qzuw** [comment]
public link seems to be https://helda.helsinki.fi/items/9f681533-f488-406d-b2d8-a2f8b225f283
