### ISSUE TITLE
Copying commands include dollar sign $

### ISSUE THREAD

**Issue by mom3d** [docker-hy/docker-hy.github.io#258]
#### Description
When copying command code from the tutorial page, the copied text includes the dollar sign (`$`). This causes issues when pasting the command into a terminal, as the dollar sign is not part of the command but a prompt indicator.

#### Steps to Reproduce
1. Navigate to the tutorial page at https://devopswithdocker.com/part-1/section-2.
2. Find a code block with a command prompt.
3. Highlight and copy the command, which looks like:
    ```sh
    $ some-command --with-parameters
    ```
4. Paste the copied text into a terminal.

#### Expected Behavior
The copied text should exclude the dollar sign, so when pasted into the terminal, it should look like this:
```sh
some-command --with-parameters

**Comment by qzuw** [comment]
$ (or # for root) is fairly common convention in tutorials, especially if there is mix of user input and command output in the examples. Usually (in my past experience, and few quick searches right now) these also copy dollar sign.

As a workaround, you could just highlight the actual command you want to copy, without initial dollar sign.
