### ISSUE TITLE
Exercise 2.4 from part 2 doesnt work with WSL 2

### ISSUE THREAD

**Issue by zephimir** [docker-hy/docker-hy.github.io#60]
So far all the exercises worked well but I got stuck on 2.4 using WSL. I managed to make it work on my linux computer though. 

The "responses" are never started even when scaling multiple compute containers

**Comment by Jakousa** [comment]
Thanks. I'll check WSL 2 in the, hopefully near, future.

**Comment by zephimir** [comment]
I'm an idiot I installed docker directly on my distro instead of using windows docker with WSL2 support. It actually works this way.
