### ISSUE TITLE
Part 3 material mismatch with Part 1 exercises

### ISSUE THREAD

**Issue by markku63** [docker-hy/docker-hy.github.io#77]
The text of part 3 states: 

> Every Dockerfile we’ve used until now has been FROM ubuntu

However, in exercises 1.13 and 1.14 we were told to create Dockerfiles from openjdk and Ruby images instead of ubuntu. The exercises in parts 1 and 2 using the node.js based frontend/backend don't specifically state that Dockerfiles should start from ubuntu images,  so I used FROM node which makes exercise 3.1 difficult.

**Comment by Jakousa** [comment]
Thanks for the notice. I fixed this when rewriting the sections.
