### ISSUE TITLE
Part 2 scaling example (possibly) has faulty IP-address

### ISSUE THREAD

**Issue by juhojo** [docker-hy/docker-hy.github.io#81]
There is a short section after Exercise 2.3 discussing scaling.

In one of the code-blocks there is an example of cURLing some ports. However, the IP-address of these cURLs is `0.0.0.0:<some-port>`, while I believe they should be the loopback address referring to the host (`127.0.0.1:<some-port>`)?

While I do think that the 0.0.0.0 *should* work, it does not on my Windows 10 device (big surprise). Could this IP-address be changed in the material or is there a reason why the `0.0.0.0`-address is superior?

![image](https://user-images.githubusercontent.com/9413310/91722790-71395200-eba3-11ea-919c-a4d0ecd3251b.png)
A screenshot of the section in discussion.

**Comment by qzuw** [comment]
My system seems to translate 0.0.0.0 to 127.0.0.1 automatically, but in principle 127.0.0.1 is more correct, I think.
