### ISSUE TITLE
Exercise 2.6 postgres docker hub URL is not valid

### ISSUE THREAD

**Issue by jutunen** [docker-hy/docker-hy.github.io#86]
[https://hub.docker.com//_/postgres/](https://hub.docker.com//_/postgres/) gives 404

**Comment by fabianhick** [comment]
This seems to have been fixed in #80.
However, it appears as if those changes haven't been deployed yet.

Is there a reason for that, @Jakousa?

**Comment by Jakousa** [comment]
I believe there was some goofing happening with the escapes in the link itself and/or another PR that changed it backwards. I may have accepted some broken PRs on top of yours without testing them myself 👀  Should be ok now!
