### ISSUE TITLE
Youtube-dl has been taken down from Github

### ISSUE THREAD

**Issue by tkt20** [docker-hy/docker-hy.github.io#87]
Seems like there are some legal problems (https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md). You can still download it from http://yt-dl.org/ so it is not affecting part1 examples yet.

**Comment by Jakousa** [comment]
Thanks for the heads up. I followed the status and it seems youtube dl is back. They've removed all references to copyrighted material https://github.com/ytdl-org/youtube-dl

Our examples use my own content (created and uploaded by me) from imgur which doesn't prohibit downloading content.
