### ISSUE TITLE
Fix finnish national id format

### ISSUE THREAD

**Issue by Jaakkonen** [docker-hy/docker-hy.github.io#99]
Currently the Finnish social security number is formatted as `xxxxxx-xxxx` in [completion.md](https://github.com/docker-hy/docker-hy.github.io/blob/master/pages/completion.md).

However that doesn't include people born in the 2000's who have a 'A' instead of '-'.

Maybe replace that as a more informative format like `ddmmyy[-/A]XXXY`.

More info if deemed useful: `dd` is day (01-31), `mm` month (01-12), `yy` year, `-/A` is `-` for persons born in 1900's and `A` for 2000's. `XXX` is individual number (integers) and `Z` a checksum of range `[0-9A-FHJ-NPR-Y]`.

**Comment by Jakousa** [comment]
Should be ok now
